### ISSUE TITLE
Error: Feed Format Error: Entry Missing Date

### ISSUE THREAD

**Issue by Kerinlin** [luyuhuang/vscode-rss#15]
https://rsshub.app/github/trending/daily/javascript

我尝试添加这个，然后报错

**Comment by luyuhuang** [comment]
这个源缺少日期字段, 目前阅读器认为这个字段是必要的. 不过我查了下 rss 2.0 规范, pubDate 确实是个可选字段, 这里应该加个容错.

**Comment by luyuhuang** [comment]
v0.7.2 修复了这个问题
