### ISSUE TITLE
I am not able to paste feed URL

### ISSUE THREAD

**Issue by gemad** [luyuhuang/vscode-rss#19]
when I click on the plus to add feed I am not able to Ctr+v here, Nothing happen, and using the right click hide the box 

## Note : 
 This problem happens only if the the marketplace tap is in focus (currently active) ! strange right :D ?
---

![image](https://user-images.githubusercontent.com/10174770/94375997-eef76b80-0117-11eb-8abc-7ffa4aeef45d.png)

```
Version: 1.48.1
Commit: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
Date: 2020-08-19T17:12:13.244Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763
```

**Comment by luyuhuang** [comment]
My vscode version is 1.49.2, which doesn't have this problem. Then I downloaded 1.48.1 and found I can't even paste in the file search box when marketplace tap is in focus 😂. It should be a vscode's bug, maybe you should upgrade your vscode.

**Comment by gemad** [comment]
vscode bug
