### ISSUE TITLE
'Error: Feed Format Error: Entry Missing Content' is raised.

### ISSUE THREAD

**Issue by septsea** [luyuhuang/vscode-rss#2]
Whenever I want to subscribe to https://code.visualstudio.com/feed.xml, the error (as the title mentions) is raised. Rolly (an Android RSS reader) works well.

**Comment by luyuhuang** [comment]
Generally HTML contents should be placed in CDATA, or escape angle brackets `<` and `>`. But this feed didn't do so. It may be that we should stop parsing the XML when we encounters a tag with the attribute `type="html"`, but the XML parser we use, fast-xml-parser, is not support it yet. Give me some time to study this problem.

**Comment by septsea** [comment]
Thank you!

By the way, the article page is always refreshed if I leave it. (Is this a feature?)

Also, the pictures are displayed out of proportion.

Your extension is so nice! I have uninstalled other RSS readers.

Though it is simple (compared to those readers), I still enjoy it very much.

**Comment by luyuhuang** [comment]
The page is always refreshed due to the limitation of vscode, you can found that the release notes page also have the same problem. For the picture that out of proportion, I'll try to fix the bug, you can open an issue and attach this feed's URL.

**Comment by luyuhuang** [comment]
> @septsea 
> By the way, the article page is always refreshed if I leave it. (Is this a feature?)

v0.3.0 fixed this problem.

**Comment by septsea** [comment]
> @luyuhuang 
> v0.3.0 fixed this problem.

Thanks so much!

**Comment by luyuhuang** [comment]
I opened a pr on fast-xml-parser: https://github.com/NaturalIntelligence/fast-xml-parser/pull/257 . This problem can be solved after this pr is merged.

**Comment by septsea** [comment]
> @luyuhuang 
> I opened a pr on fast-xml-parser: [NaturalIntelligence/fast-xml-parser#257](https://github.com/NaturalIntelligence/fast-xml-parser/pull/257) . This problem can be solved after this pr is merged.

Thank you!

**Comment by crazycliffy** [comment]
I've upvoted this issue.  Yes would like to see if vscode's rss feed can be opened up.  I was only able to open Visual Studio Blog rss feed.  The link below shows where I got the feed.

https://blog.feedspot.com/visual_studio_rss_feeds/

keep up the good work on this extension, I use it everyday to check. 😊

**Comment by luyuhuang** [comment]
v0.6.0 fixes this problem, using a temporary method.
