### ISSUE TITLE
如果能导出收藏夹和订阅就好了.

### ISSUE THREAD

**Issue by chaleaoch** [luyuhuang/vscode-rss#20]

**Comment by luyuhuang** [comment]
希望导出成什么格式呢? 订阅列表可以导出成 opml, 收藏夹呢?

**Comment by chaleaoch** [comment]
其实是导出+导入, 
导出的格式导入识别就好了
其实就是切换vscode的时候, 能够手动同步local账户.

**Comment by luyuhuang** [comment]
可以

**Comment by whyouare111** [comment]
> 
> 
> 希望导出成什么格式呢? 订阅列表可以导出成 opml, 收藏夹呢?

收藏夹用各个浏览器导入导出书签的html格式如何呢？感觉是可以满足的
https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa753582(v=vs.85)?redirectedfrom=MSDN

**Comment by luyuhuang** [comment]
> 收藏夹用各个浏览器导入导出书签的html格式如何呢？感觉是可以满足的

恐怕不行, 导出的内容得包含文章正文才行, 要不然的话导入后怎么阅读它呢?
