### ISSUE TITLE
specific feed is not resolved

### ISSUE THREAD

**Issue by amigo421** [luyuhuang/vscode-rss#29]
[this](http://scrutator.me/syndication.axd) feed is not resolved by extension

**Comment by amigo421** [comment]
one unresolved [feed](https://www.justsoftwaresolutions.co.uk/index.rss)

**Comment by luyuhuang** [comment]
For http://scrutator.me/syndication.axd, the error "incorrect header check" due to incorrect compression format, but anyway there is a way to fix it. However, besides this problem, this feed also has a bad date format that the program cannot recognize:

```
<pubDate>Пн, 30 июл 2018 14:30:00 +0300</pubDate>
```

**Comment by amigo421** [comment]
comparing with inoreader , there was no issue with a format, seems this is local russian formatting which includes even week day as prefix

**Comment by luyuhuang** [comment]
I know. Let me find if have any way to parse internationalized date format.

**Comment by luyuhuang** [comment]
Parsing internationalized date is not an easy task, I have opened a new issue.
