### ISSUE TITLE
The pictures are displayed out of proportion.

### ISSUE THREAD

**Issue by septsea** [luyuhuang/vscode-rss#3]
_(This issue continues from #2. Maybe I could raise the refresh issue at vscode's repository.)_

Feed: [https://www.ifanr.com/feed](https://www.ifanr.com/feed)

Article: the article whose title contains 'XPS 13-9300'

The original link is [https://www.ifanr.com/1333620](https://www.ifanr.com/1333620).

Thank you!

**Comment by luyuhuang** [comment]
Version 0.2.2 fixed this bug. For old articles, you must remove them and update again.

**Comment by septsea** [comment]
Good morning. Thank you! Nice!
