### ISSUE TITLE
Wrong rendering embedded code

### ISSUE THREAD

**Issue by amigo421** [luyuhuang/vscode-rss#30]
https://devblogs.microsoft.com/cppblog/abbreviated-function-templates-and-constrained-auto/

see in the extension:
![image](https://user-images.githubusercontent.com/3259933/107221413-ab493280-6a24-11eb-868b-d532ccd3c065.png)

and on the page:
![image](https://user-images.githubusercontent.com/3259933/107221486-c320b680-6a24-11eb-84d4-58c9d2237730.png)

**Comment by luyuhuang** [comment]
Well, this problem is really hard to resolve. Please give me some time.

**Comment by luyuhuang** [comment]
v0.10.0 fixed this problem.
