### ISSUE TITLE
Existing articles in non-account based feed do not get updated if they change

### ISSUE THREAD

**Issue by ikannak** [luyuhuang/vscode-rss#38]
I'm investigating your extension for use as an RSS feed extension for a VS Code environment which should report items on an RSS feed that might change. More specifically: the RSS feed shows the 10 most recent build server actions, showing a few specific details and their status. This status can change, and we'd like our developers to get updated when this status changes. However, with your reader, any existing RSS items do not get updated in the local view when they're updated in the feed. We're looking for a fully local solution because the RSS feed is usually not available from outside the network, so we're unable to use an external account or service like InoReader or TTRSS.

Is this feature something you'd consider adding?

**Comment by luyuhuang** [comment]
No problem.

**Comment by luyuhuang** [comment]
v0.10.1 implemented this feature.
