### ISSUE TITLE
Feature Request for Tiny Tiny RSS account

### ISSUE THREAD

**Issue by hoilc** [luyuhuang/vscode-rss#4]
- hide read feeds
- display the hierarchy of categories and feeds

**Comment by luyuhuang** [comment]
> - hide read feeds

Is it ok to add a view to show unread articles?

> - display the hierarchy of categories and feeds

I try to add a feature to categorize feeds. This may take some time.

**Comment by hoilc** [comment]
> > * hide read feeds
> 
> Is it ok to add a view to show unread articles?
> 

Sure. It's ideal to switch views with shortcuts.

Thanks.😀

**Comment by luyuhuang** [comment]
v0.5.0 implements these features.
