### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by SkyNetX007** [luyuhuang/vscode-rss#45]
更新订阅时失败，提示证书过期（RequestError: certificate has expired）。

经检查，出问题的均是 Let's Encrypt 签发的证书，怀疑是之前 Let's Encrypt 根证书于 2021/9/30 过期的问题，但浏览器访问正常。

**Comment by luyuhuang** [comment]
能提供下有问题的 URL 吗

**Comment by SkyNetX007** [comment]
https://rsshub.uneasy.win/twitter/user/DIYgod

**Comment by luyuhuang** [comment]
你可以尝试下这个: [rss.zip](https://github.com/luyuhuang/vscode-rss/files/7616408/rss.zip). 解压缩后会得到一个 vsix 文件, 在 vscode 的 extension 界面选择 "Install from VSIX..." 并选择这个 vsix 文件进行安装.

![image](https://user-images.githubusercontent.com/10300685/143828742-056fdaf9-8133-478d-8c94-bde195ae2762.png)

**Comment by luyuhuang** [comment]
这好像是 vscode 的一个 bug: https://github.com/microsoft/vscode/issues/136787 . 你可以尝试设置 `http.systemCertificates: false` 看看能不能解决这个问题.

**Comment by SkyNetX007** [comment]
`http.systemCertificates: false` 确实有效，就等 VSCode 和 Electron 修复这个 BUG 了.
