### ISSUE TITLE
Limit of 20 unread articles?

### ISSUE THREAD

**Issue by Gruntfuggly** [luyuhuang/vscode-rss#46]
I'm using this synced to my inoreader account and it seems that it only shows a maximum of 20 unread articles for any feeds. Any other unread articles don't appear.

Is this something that can be changed?

**Comment by luyuhuang** [comment]
Yes, the inoreader API's default limit is 20, but it max to 1000. I can make the limit configurable.

**Comment by Gruntfuggly** [comment]
That would be awesome - thank you!

**Comment by luyuhuang** [comment]
No problem

**Comment by luyuhuang** [comment]
v0.10.3 implements this feature.

**Comment by Gruntfuggly** [comment]
Thank you - works very nicely!
