### ISSUE TITLE
Are these RSS Feeds supported?

### ISSUE THREAD

**Issue by crazycliffy** [luyuhuang/vscode-rss#5]
Hi, I tried at these public feeds, but not sure why they don't work.  Are they supported by your parser?

https://hub.spigotmc.org/jenkins/rssAll
http://jenkins.movingblocks.net/rssFailed

I used your example from [node.js blog](https://nodejs.org/en/feed/blog.xml) and that worked out fine.

**Comment by luyuhuang** [comment]
Both two feeds are missing article content. Well, maybe it ’s better to be compatible with this format. I'll fix this problem soon.

**Comment by luyuhuang** [comment]
v0.5.0 fixes this bug.

**Comment by crazycliffy** [comment]
really appreciate your support on this. thank you.  I updated to v0.5.0 (2020-05-31), but didn't see the fix.  Is it in that build?

**Comment by luyuhuang** [comment]
Well, it must re-fetch the feed content and re-parse it, because I changed the parser. I think you can just click the refresh button.
