### ISSUE TITLE
Error: Feed Format Error: Entry Missing Link

### ISSUE THREAD

**Issue by trotsky1997** [luyuhuang/vscode-rss#6]

**Comment by trotsky1997** [comment]
http://rss.huanqiu.com/topnews.xml

**Comment by luyuhuang** [comment]
This bug has been fixed. I'll release a new version later.

**Comment by trotsky1997** [comment]
> This bug has been fixed. I'll release a new version later.

Thanks!

**Comment by trotsky1997** [comment]
> This bug has been fixed. I'll release a new version later.

This feed is still "Error: Feed Format Error: Entry Missing Link"
https://rsshub.ioiox.com/guanchazhe/index/all
