### ISSUE TITLE
Error: Feed Format Error: Entry Missing Link

### ISSUE THREAD

**Issue by trotsky1997** [luyuhuang/vscode-rss#7]
This feed is still "Error: Feed Format Error: Entry Missing Link"
https://rsshub.ioiox.com/guanchazhe/index/all
I have updated to latest version.

**Comment by luyuhuang** [comment]
There is indeed an entry with no link:

```xml
<item>
<title>
<![CDATA[ “北京疫情不能看作是第二波疫情来临” ]]>
</title>
<description>
<![CDATA[ null<br><a href="https://www.guancha.cn/politics/2020_06_21_554898.shtml" target="_blank"><img src="https://www.guancha.cn/undefined" referrerpolicy="no-referrer"><br>【全文阅读】</a> ]]>
</description>
<pubDate>Sat, 20 Jun 2020 16:00:00 GMT</pubDate>
<guid isPermaLink="false">554898</guid>
<link/>
<author>
<![CDATA[ 首页Feeds中间+右边2列 ]]>
</author>
<category>首页Feeds中间+右边2列</category>
</item>
```

vscode-rss uses the link as the identifier of the article, so the link is required. I know it isn't a good design, but this is a historical problem that is not easy to solve... 😂 Give me time to think of a way.

**Comment by trotsky1997** [comment]
> There is indeed an entry with no link:
> 
> ```
> <item>
> <title>
> <![CDATA[ “北京疫情不能看作是第二波疫情来临” ]]>
> </title>
> <description>
> <![CDATA[ null<br><a href="https://www.guancha.cn/politics/2020_06_21_554898.shtml" target="_blank"><img src="https://www.guancha.cn/undefined" referrerpolicy="no-referrer"><br>【全文阅读】</a> ]]>
> </description>
> <pubDate>Sat, 20 Jun 2020 16:00:00 GMT</pubDate>
> <guid isPermaLink="false">554898</guid>
> <link/>
> <author>
> <![CDATA[ 首页Feeds中间+右边2列 ]]>
> </author>
> <category>首页Feeds中间+右边2列</category>
> </item>
> ```
> 
> vscode-rss uses the link as the identifier of the article, so the link is required. I know it isn't a good design, but this is a historical problem that is not easy to solve... 😂 Give me time to think of a way.
大佬,您编译后的js加了混淆吗

**Comment by luyuhuang** [comment]
没有啊, webpack 了而已

**Comment by trotsky1997** [comment]
用缺省值替换报错可以解决，提高对rss源的兼容性。
我修改了Parser.ts 已经PR了

**Comment by trotsky1997** [comment]
![image](https://user-images.githubusercontent.com/30512160/85230126-a34e6b00-b420-11ea-83b4-9e32a85741ea.png)
